main: main.o
	gcc -ansi -Wall -pedantic -g main.o -o main
main.o: main.c
	gcc -c -ansi -g -Wall -pedantic main.c -o main.o

sort: sort.o
	gcc -ansi -Wall -pedantic -g sort.o -o sort
sort.o: sort.c
	gcc -c -ansi -g -Wall -pedantic sort.c -o sort.o
